1675944905.3925893
MNH3 5.5960568598020926
FLOT 0.058142760406116385
OGKB 0.0005597441734330504
AKRN 43.26509835309063
MTLRP 0.19733410096566992
RASP 0.2431932315205242
YNH3 20.072591674216913
UPRO 0.0020733308023300353
CBOM 0.00551298831762543
SMLT 1.9174327596929466
MTLR 0.11882419933576227
KMAZ 0.20822078685673237
SGZH 0.00419250821625194
SNH3 34.23292643305336
ISKJ 0.21588423884934224
DSKY 0.050916897323188604
RNFT 0.3329046958691945
SIBN 0.2752449545311136
LKH3 23.464860206407675
GKH3 8.666533065363264
TRMK 0.07691780999390771
INGR 4.368345758053907
BELU 2.8921615604157718
BSPB 0.4141363247340276
POH3 7.210152570316
BANEP 1.0960203775703647
MVID 0.2446332117634199
SPH3 12.322564906211062
RNH3 31.453813917920655
FEES 9.234846057816989e-05
PZH3 138.2586439216441
LSRG 0.45881800224454455
OZH3 37.1419268773813
LENT 1.0088957984918356
NMH3 17.658510955220518
CHH3 239.36404754125857
FESH 0.030423928750703183
TRNFP 164.83359845452833
HYDR 0.0004002942152503797
RMH3 0.7981076270448512
VBH3 1.535509662025778
PIKK 0.35388177731090037
MXH3 96.73485724816848
SNGS 0.018086131173277155
SNGSP 0.017843833199734458
EuH3 25.21492166255079
MTSS 0.16360299084170538
POSI 1.2851596192906642
GZH3 9.854035007579867
SPBE 0.23366944193353423
GMKN 6.6585910014776815
PHOR 5.548304476255942
IRAO 0.0016818375081983834
MGNT 3.1192700396347175
MOEX 0.05709703320988896
AFKS 0.01048340837664714
NLMK 0.07479194418207169
TATNP 0.14703908875841828
RUAL 0.03343243069779215
SBERP 0.09220989830369193
MAGN 0.025432001401089945
AFLT 0.024678892743018474
ALRS 0.03599837423146262
CHMF 0.8831134437600857
PLZL 7.6491538271431185
TATN 0.15198974887798428
LKOH 1.7820992296920815
NVTK 0.823950743925324
VTBR 1.0994561816083562e-05
SBER 0.10463783276957164
ROSN 0.28765598687781285
GAZP 0.09037500443610755
EDH3 0.00022365471494777418
RIH3 49.701985309945115
CRH3 0.003286280474923227
SRH3 10.203641240229055
SiH3 20.44039608231448
Traceback (most recent call last):
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
    with util.safe_reraise():
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oleg/PycharmProjects/trading/update_levels.py", line 228, in <module>
    update_db_tables(df_levels, df_all_levels, df_all_volumes)
  File "/home/oleg/PycharmProjects/trading/update_levels.py", line 217, in update_db_tables
    df_levels.to_sql('df_levels', engine, if_exists='replace')
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 2951, in to_sql
    return sql.to_sql(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 697, in to_sql
    return pandas_sql.to_sql(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 1729, in to_sql
    table = self.prep_table(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 1628, in prep_table
    table.create()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 831, in create
    if self.exists():
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 815, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 1762, in has_table
    insp = inspect(self.connectable)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/inspection.py", line 64, in inspect
    ret = reg(subject)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
    init(self, bind)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
    engine.connect().close()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
    with util.safe_reraise():
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/oleg/PycharmProjects/trading/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
